version: "3.3"

services:
  app:
    container_name: inergy-uc13-dashboard
    image: inergy-uc13-dashboard
    restart: always
    build:
      context: ""
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true
    env_file:
      - config/.env-epu