export const multilingual = {
    english: {
        layout: {
            menuItem1: 'Homepage',
            menuItem2: 'Plan Investment',
            menuItem3: 'Energy Admin Measures Admin Page',
            menuItem4: 'My Profile',
            menuItem5: 'Sign Out',
            welcome: 'Welcome',
            copyright: `Copyright I-NERGY Consortium @${new Date().getFullYear()} All rights reserved`,
            eu_msg: 'Co-funded by the Horizon 2020 Framework Programme of the European Union Under grant agreement No 101016508',
        },
        homepage: {
            serviceTitle1: 'Issue your virtual EPC',
            serviceDesc1: 'Energy Performance Certificate quickly and easily via a user intuitive UI.',
            serviceTitle2: 'Visualize energy savings',
            serviceDesc2: 'Charts and useful information about your energy savings.',
        },
        planInvestment: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'Plan Investment',
            pageTitle: 'Energy Efficiency Investment De-RiskingEnergy Efficiency Investment De-Risking',
            configuration: 'Configuration',
            sectionTitle1: 'Select Building Address',
            sectionDesc1: 'Fill in the dropdown menu with the proper address to open the map.',
            sectionPlaceholder1: 'Address',
            sectionTitle2: 'Choose a resembling photo',
            sectionDesc2: 'Select the image that looks like your building the most. In this way, the system will understand its characteristics.',
            sectionTitle3: 'Building Location & Surroundings',
            sectionDesc3: 'A map displaying the chosen building\'s location.',
            sectionWarn3: 'Please select an address first!',
            perimeter: 'Perimeter',
            button: 'Virtual EPC',
        },
        selectInvestment: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'Plan Investment',
            breadcrumb3: 'Virtual EPC & Innovation Measures',
            pageTitle: 'Energy Efficiency Investment De-Risking',
            general: 'General information',
            clickDetails: 'Click for details',
            energyClass: 'Energy Class',
            totalConsumption: 'Total Energy Consumption',
            measures: 'Energy Efficiency Measures',
            totalCost: 'Total Cost',
            expected: 'Expected Results',
            tryOther: 'Want to try other measures?',
            yesModal: 'Yes, try other measures.',
            noModal: 'No, back to service page.',
            button: 'Calculate',
        },
        adminPage: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'Energy Measures Admin page',
            pageTitle: 'Energy Efficiency Investment De-Risking',
            rows: 'Rows per page',
            save: 'SAVE',
            reset: 'RESET',
            delete: 'DELETE'
        },
        myProfile: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'User Profile',
            current_user: 'Currently logged in user',
            clickDetails: 'Click for details',
            username: 'Username',
            roles: 'Roles',
            first_name: 'First Name',
            last_name: 'Last Name',
            expand: 'Click to expand',
            noRoles: 'No roles assigned',
            role_singular: 'role',
            role_plural: 'roles'
        },
    },
    latvian: {
        layout: {
            menuItem1: 'Mājas lapa',
            menuItem2: 'Pasākumu plānošana',
            menuItem3: 'Energoefektivitātes pasākumu administratora sadaļa',
            menuItem4: 'Mans profils',
            menuItem5: 'Izrakstīties',
            welcome: 'Laipni lūdzam',
            copyright: `Autortiesības I-NERGY konsorcijs @${new Date().getFullYear()} Visas tiesības aizsargātas`,
            eu_msg: 'Līdzfinansē Eiropas Savienības pamatprogramma "Apvārsnis 2020" saskaņā ar dotāciju nolīgumu Nr. 101016508.',
        },
        homepage: {
            serviceTitle1: 'Izsniedziet savu virtuālo Ēkas energosertifikātu',
            serviceDesc1: 'Energoefektivitātes sertifikāts ātri un vienkārši, izmantojot lietotājam draudzīgu lietotāja saskarni.',
            serviceTitle2: 'Enerģijas ietaupījuma vizualizēšana',
            serviceDesc2: 'Diagrammas un noderīga informācija par enerģijas ietaupījumu.',
        },
        planInvestment: {
            breadcrumb1: 'Mājas lapa',
            breadcrumb2: 'Plānot ieguldījumus',
            pageTitle: 'Investīciju riska mazināšana uzlabojot  energoefektivitāti',
            configuration: 'Konfigurācija',
            sectionTitle1: 'Atlasiet ēkas adresi',
            sectionDesc1: 'Lai atvērtu karti, nolaižamajā izvēlnē ievadiet pareizo adresi.',
            sectionPlaceholder1: 'Adrese',
            sectionTitle2: 'Izvēlieties līdzīgu fotoattēlu',
            sectionDesc2: 'Izvēlieties attēlu, kas visvairāk atgādina jūsu ēku. Tādējādi sistēma sapratīs ēkas rakstumlielumus.',
            sectionTitle3: 'Ēkas atrašanās vieta un apkārtne',
            sectionDesc3: 'Karte, kurā redzama izvēlētās ēkas atrašanās vieta.',
            sectionWarn3: 'Lūdzu, vispirms izvēlieties adresi!',
            perimeter: 'Perimetrs',
            button: 'VIRTUĀLAIS ĒKAS ENERGOSERTIFIKĀTS',
        },
        selectInvestment: {
            breadcrumb1: 'Mājas lapa',
            breadcrumb2: 'Plānot ieguldījumus',
            breadcrumb3: 'Virtuālais ēkas energosertifikāts un inovāciju pasākumi',
            pageTitle: 'Energoefektivitātes investīciju risku mazināšana',
            general: 'Vispārīga informācija',
            clickDetails: 'LAT Click for details',
            energyClass: 'LAT Energy Class',
            totalConsumption: 'LAT Total Energy Consumption',
            measures: 'LAT Energy Efficiency Measures',
            totalCost: 'LAT Total Cost',
            expected: 'LAT Expected Results',
            tryOther: 'LAT Want to try other measures?',
            yesModal: 'LAT Yes, try other measures.',
            noModal: 'LAT No, back to service page.',
            button: 'LAT Calculate',
        },
        adminPage: {
            breadcrumb1: '',
            breadcrumb2: '',
            pageTitle: '',
            rows: '',
            save: '',
            reset: '',
            delete: ''
        },
        myProfile: {
            breadcrumb1: 'Mājas lapa',
            breadcrumb2: 'Lietotāja profils',
            current_user: 'Aktīvais lietotājs',
            clickDetails: 'Noklikšķiniet, lai iegūtu detaļas',
            username: 'Lietotājvārds',
            roles: 'Lomas',
            first_name: 'Vārds',
            last_name: 'Uzvārds',
            expand: 'Noklikšķiniet, lai paplašinātu',
            noRoles: 'Nav piešķirtu lomu',
            role_singular: 'Loma',
            role_plural: 'Lomas'
        },
    }
}