export const multilingual = {
    english: {
        layout: {
            menuItem1: 'Homepage',
            menuItem2: 'Plan Investment',
            menuItem3: 'Energy Admin Measures Admin Page',
            menuItem4: 'My Profile',
            menuItem5: 'Sign Out',
            welcome: 'Welcome',
            copyright: `Copyright I-NERGY Consortium @${new Date().getFullYear()} All rights reserved`,
            eu_msg: 'Co-funded by the Horizon 2020 Framework Programme of the European Union Under grant agreement No 101016508',
        },
        homepage: {
            serviceTitle1: 'Issue your virtual EPC',
            serviceDesc1: 'Energy Performance Certificate quickly and easily via a user intuitive UI.',
            serviceTitle2: 'Visualize energy savings',
            serviceDesc2: 'Charts and useful information about your energy savings.',
        },
        planInvestment: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'Plan Investment',
            pageTitle: 'Energy Efficiency Investment De-RiskingEnergy Efficiency Investment De-Risking',
            configuration: 'Configuration',
            sectionTitle1: 'Select Building Address',
            sectionDesc1: 'Fill in the dropdown menu with the proper address to open the map.',
            sectionPlaceholder1: 'Address',
            sectionTitle2: 'Choose a resembling photo',
            sectionDesc2: 'Select the image that looks like your building the most. In this way, the system will understand its characteristics.',
            sectionTitle3: 'Building Location & Surroundings',
            sectionDesc3: 'A map displaying the chosen building\'s location.',
            sectionWarn3: 'Please select an address first!',
            perimeter: 'Perimeter',
            button: 'Virtual EPC',
        },
        selectInvestment: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'Plan Investment',
            breadcrumb3: 'Virtual EPC & Innovation Measures',
            pageTitle: 'Energy Efficiency Investment De-Risking',
            general: 'General information',
            clickDetails: 'Click for details',
            energyClass: 'Energy Class',
            totalConsumption: 'Total Energy Consumption',
            measures: 'Energy Efficiency Measures',
            totalCost: 'Total Cost',
            expected: 'Expected Results',
            tryOther: 'Want to try other measures?',
            yesModal: 'Yes, try other measures.',
            noModal: 'No, back to service page.',
            button: 'Calculate',
        },
        adminPage: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'Energy Measures Admin page',
            pageTitle: 'Energy Efficiency Investment De-Risking',
            rows: 'Rows per page',
            save: 'SAVE',
            reset: 'RESET',
            delete: 'DELETE'
        },
        myProfile: {
            breadcrumb1: 'Homepage',
            breadcrumb2: 'User Profile',
            current_user: 'Currently logged in user',
            username: 'Username',
            roles: 'Roles',
            first_name: 'First Name',
            last_name: 'Last Name',
            expand: 'Click to expand',
            role_singular: 'role',
            role_plural: 'roles'
        },
    },
    latvian: {
        layout: {
            menuItem1: 'sasasasaasa',
            menuItem2: 'aa',
            menuItem3: 's',
            menuItem4: 's',
            menuItem5: 'x',
            welcome: 'ccc',
            copyright: `LAT Copyright I-NERGY Consortium @${new Date().getFullYear()} All rights reserved`,
            eu_msg: 'aaddd',
        },
        homepage: {
            serviceTitle1: 'LATVIAN',
            serviceDesc1: 'aasdsddsds',
            serviceTitle2: 'sasasasasassss',
            serviceDesc2: 'nnnnnnnnnnn',
        },
        planInvestment: {
            breadcrumb1: ' LAT Homepage',
            breadcrumb2: ' LAT Plan Investment',
            pageTitle: ' LAT Energy Efficiency Investment De-RiskingEnergy Efficiency Investment De-Risking',
            configuration: ' LAT Configuration',
            sectionTitle1: ' LAT Select Building Address',
            sectionDesc1: ' LAT Fill in the dropdown menu with the proper address to open the map.',
            sectionPlaceholder1: ' LAT Address',
            sectionTitle2: ' LAT Choose a resembling photo',
            sectionDesc2: ' LAT Select the image that looks like your building the most. In this way, the system will understand its characteristics.',
            sectionTitle3: ' LAT Building Location & Surroundings',
            sectionDesc3: ' LAT A map displaying the chosen building\'s location.',
            sectionWarn3: ' LAT Please select an address first!',
            perimeter: ' LAT Perimeter',
            button: ' LAT Virtual EPC',
        },
        selectInvestment: {
            breadcrumb1: 'LAT Homepage',
            breadcrumb2: 'LAT Plan Investment',
            breadcrumb3: 'LAT Virtual EPC & Innovation Measures',
            pageTitle: 'LAT Energy Efficiency Investment De-Risking',
            general: 'LAT General information',
            clickDetails: 'LAT Click for details',
            energyClass: 'LAT Energy Class',
            totalConsumption: 'LAT Total Energy Consumption',
            measures: 'LAT Energy Efficiency Measures',
            totalCost: 'LAT Total Cost',
            expected: 'LAT Expected Results',
            tryOther: 'LAT Want to try other measures?',
            yesModal: 'LAT Yes, try other measures.',
            noModal: 'LAT No, back to service page.',
            button: 'LAT Calculate',
        },
        adminPage: {
            breadcrumb1: '',
            breadcrumb2: '',
            pageTitle: '',
            rows: '',
            save: '',
            reset: '',
            delete: ''
        },
        myProfile: {
            breadcrumb1: '',
            breadcrumb2: '',
            current_user: '',
            username: '',
            roles: '',
            first_name: '',
            last_name: '',
            expand: '',
            role_singular: '',
            role_plural: ''
        },
    }
}